INFO - UNet_Speech_Separation - Running command 'do_experiment'
INFO - UNet_Speech_Separation - Started run with ID "28"
Experiment ID: 28
Preparing dataset
2018-08-15 12:25:56.460980: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-08-15 12:25:56.542756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Quadro K4200 major: 3 minor: 0 memoryClockRate(GHz): 0.784
pciBusID: 0000:84:00.0
totalMemory: 3.94GiB freeMemory: 188.00MiB
2018-08-15 12:25:56.614581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties: 
name: Quadro K4200 major: 3 minor: 0 memoryClockRate(GHz): 0.784
pciBusID: 0000:88:00.0
totalMemory: 3.94GiB freeMemory: 3.87GiB
2018-08-15 12:25:56.614743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2018-08-15 12:25:56.614783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1 
2018-08-15 12:25:56.614794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y 
2018-08-15 12:25:56.614800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y 
2018-08-15 12:25:56.614811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro K4200, pci bus id: 0000:84:00.0, compute capability: 3.0)
2018-08-15 12:25:56.614820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: Quadro K4200, pci bus id: 0000:88:00.0, compute capability: 3.0)
Creating model
Loading checkpoint
INFO:tensorflow:Restoring parameters from /home/enterprise.internal.city.ac.uk/acvn728/checkpoints/25/25-10
INFO - tensorflow - Restoring parameters from /home/enterprise.internal.city.ac.uk/acvn728/checkpoints/25/25-10
2018-08-15 12:26:02.485292: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 59.00M (61865984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.495544: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 53.10M (55679488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.498950: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 47.79M (50111744 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.507567: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 43.01M (45100800 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.510960: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 38.71M (40590848 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.517017: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 34.84M (36531968 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.520630: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 31.36M (32878848 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.528362: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 30.78M (32274944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.533054: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 30.78M (32274944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.539558: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 30.78M (32274944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:02.544210: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 30.78M (32274944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:03.714341: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 30.78M (32274944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-08-15 12:26:03.718289: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 30.78M (32274944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
