{
  "artifacts": [],
  "command": "do_experiment",
  "experiment": {
    "base_dir": "/home/enterprise.internal.city.ac.uk/acvn728/MScFinalProject",
    "dependencies": [
      "numpy==1.15.2",
      "sacred==0.7.4",
      "tensorflow-gpu==1.4.1"
    ],
    "mainfile": "main.py",
    "name": "UNet_Speech_Separation",
    "repositories": [],
    "sources": [
      [
        "audio_models.py",
        "_sources/audio_models_0bc7309511a05cf5508fd1615b766110.py"
      ],
      [
        "dataset.py",
        "_sources/dataset_a83ad44a54b843a850f6c265244adb8b.py"
      ],
      [
        "main.py",
        "_sources/main_c80ffd544a7e8d273bc60b08648d4e0c.py"
      ],
      [
        "train.py",
        "_sources/train_131688ebb0da6476ae60981b24a4d036.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/enterprise.internal.city.ac.uk/acvn728/.local/lib/python3.5/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"main.py\", line 110, in do_experiment\n    name='Magnitude_Model')\n",
    "  File \"/home/enterprise.internal.city.ac.uk/acvn728/MScFinalProject/audio_models.py\", line 47, in __init__\n    self.check_op = tf.add_check_numerics_ops()\n",
    "  File \"/home/enterprise.internal.city.ac.uk/acvn728/.local/lib/python3.5/site-packages/tensorflow/python/ops/numerics.py\", line 75, in add_check_numerics_ops\n    raise ValueError(\"`tf.add_check_numerics_ops() is not compatible \"\n",
    "ValueError: `tf.add_check_numerics_ops() is not compatible with TensorFlow control flow operations such as `tf.cond()` or `tf.while_loop()`.\n"
  ],
  "heartbeat": "2018-10-10T17:36:36.106115",
  "host": {
    "ENV": {},
    "cpu": "AMD Ryzen 7 1700 Eight-Core Processor",
    "gpus": {
      "driver_version": "396.44",
      "gpus": [
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11176
        },
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11178
        }
      ]
    },
    "hostname": "america",
    "os": [
      "Linux",
      "Linux-4.4.0-134-generic-x86_64-with-Ubuntu-16.04-xenial"
    ],
    "python_version": "3.5.2"
  },
  "meta": {
    "command": "do_experiment",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "model_config.checkpoint_to_load=99/99-21000"
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2018-10-10T17:34:14.700888",
  "status": "FAILED",
  "stop_time": "2018-10-10T17:36:36.112416"
}